/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	longhornv1beta2 "github.com/longhorn/longhorn-manager/k8s/pkg/apis/longhorn/v1beta2"
)

// EngineTargetStatusApplyConfiguration represents a declarative configuration of the EngineTargetStatus type for use
// with apply.
//
// EngineTargetStatus defines the observed state of the Longhorn engine target
// NOTE: This is a placeholder for the target-side status until instance-manager support is added.
type EngineTargetStatusApplyConfiguration struct {
	CurrentReplicaAddressMap map[string]string                      `json:"currentReplicaAddressMap,omitempty"`
	ReplicaModeMap           map[string]longhornv1beta2.ReplicaMode `json:"replicaModeMap,omitempty"`
	Endpoint                 *string                                `json:"endpoint,omitempty"`
}

// EngineTargetStatusApplyConfiguration constructs a declarative configuration of the EngineTargetStatus type for use with
// apply.
func EngineTargetStatus() *EngineTargetStatusApplyConfiguration {
	return &EngineTargetStatusApplyConfiguration{}
}

// WithCurrentReplicaAddressMap puts the entries into the CurrentReplicaAddressMap field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the CurrentReplicaAddressMap field,
// overwriting an existing map entries in CurrentReplicaAddressMap field with the same key.
func (b *EngineTargetStatusApplyConfiguration) WithCurrentReplicaAddressMap(entries map[string]string) *EngineTargetStatusApplyConfiguration {
	if b.CurrentReplicaAddressMap == nil && len(entries) > 0 {
		b.CurrentReplicaAddressMap = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.CurrentReplicaAddressMap[k] = v
	}
	return b
}

// WithReplicaModeMap puts the entries into the ReplicaModeMap field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ReplicaModeMap field,
// overwriting an existing map entries in ReplicaModeMap field with the same key.
func (b *EngineTargetStatusApplyConfiguration) WithReplicaModeMap(entries map[string]longhornv1beta2.ReplicaMode) *EngineTargetStatusApplyConfiguration {
	if b.ReplicaModeMap == nil && len(entries) > 0 {
		b.ReplicaModeMap = make(map[string]longhornv1beta2.ReplicaMode, len(entries))
	}
	for k, v := range entries {
		b.ReplicaModeMap[k] = v
	}
	return b
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *EngineTargetStatusApplyConfiguration) WithEndpoint(value string) *EngineTargetStatusApplyConfiguration {
	b.Endpoint = &value
	return b
}
