/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// EngineTargetSpecApplyConfiguration represents a declarative configuration of the EngineTargetSpec type for use
// with apply.
//
// EngineTargetSpec defines the desired state of the Longhorn engine target
// EngineTarget is responsible for target-side I/O serving in a separated engine design.
type EngineTargetSpecApplyConfiguration struct {
	ReplicaAddressMap map[string]string `json:"replicaAddressMap,omitempty"`
	SnapshotMaxCount  *int              `json:"snapshotMaxCount,omitempty"`
	SnapshotMaxSize   *int64            `json:"snapshotMaxSize,omitempty"`
}

// EngineTargetSpecApplyConfiguration constructs a declarative configuration of the EngineTargetSpec type for use with
// apply.
func EngineTargetSpec() *EngineTargetSpecApplyConfiguration {
	return &EngineTargetSpecApplyConfiguration{}
}

// WithReplicaAddressMap puts the entries into the ReplicaAddressMap field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ReplicaAddressMap field,
// overwriting an existing map entries in ReplicaAddressMap field with the same key.
func (b *EngineTargetSpecApplyConfiguration) WithReplicaAddressMap(entries map[string]string) *EngineTargetSpecApplyConfiguration {
	if b.ReplicaAddressMap == nil && len(entries) > 0 {
		b.ReplicaAddressMap = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ReplicaAddressMap[k] = v
	}
	return b
}

// WithSnapshotMaxCount sets the SnapshotMaxCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SnapshotMaxCount field is set to the value of the last call.
func (b *EngineTargetSpecApplyConfiguration) WithSnapshotMaxCount(value int) *EngineTargetSpecApplyConfiguration {
	b.SnapshotMaxCount = &value
	return b
}

// WithSnapshotMaxSize sets the SnapshotMaxSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SnapshotMaxSize field is set to the value of the last call.
func (b *EngineTargetSpecApplyConfiguration) WithSnapshotMaxSize(value int64) *EngineTargetSpecApplyConfiguration {
	b.SnapshotMaxSize = &value
	return b
}
