/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta2 "github.com/longhorn/longhorn-manager/k8s/pkg/apis/longhorn/v1beta2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeUpgradeManagers implements UpgradeManagerInterface
type FakeUpgradeManagers struct {
	Fake *FakeLonghornV1beta2
	ns   string
}

var upgrademanagersResource = schema.GroupVersionResource{Group: "longhorn.io", Version: "v1beta2", Resource: "upgrademanagers"}

var upgrademanagersKind = schema.GroupVersionKind{Group: "longhorn.io", Version: "v1beta2", Kind: "UpgradeManager"}

// Get takes name of the upgradeManager, and returns the corresponding upgradeManager object, and an error if there is any.
func (c *FakeUpgradeManagers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta2.UpgradeManager, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(upgrademanagersResource, c.ns, name), &v1beta2.UpgradeManager{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.UpgradeManager), err
}

// List takes label and field selectors, and returns the list of UpgradeManagers that match those selectors.
func (c *FakeUpgradeManagers) List(ctx context.Context, opts v1.ListOptions) (result *v1beta2.UpgradeManagerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(upgrademanagersResource, upgrademanagersKind, c.ns, opts), &v1beta2.UpgradeManagerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta2.UpgradeManagerList{ListMeta: obj.(*v1beta2.UpgradeManagerList).ListMeta}
	for _, item := range obj.(*v1beta2.UpgradeManagerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested upgradeManagers.
func (c *FakeUpgradeManagers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(upgrademanagersResource, c.ns, opts))

}

// Create takes the representation of a upgradeManager and creates it.  Returns the server's representation of the upgradeManager, and an error, if there is any.
func (c *FakeUpgradeManagers) Create(ctx context.Context, upgradeManager *v1beta2.UpgradeManager, opts v1.CreateOptions) (result *v1beta2.UpgradeManager, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(upgrademanagersResource, c.ns, upgradeManager), &v1beta2.UpgradeManager{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.UpgradeManager), err
}

// Update takes the representation of a upgradeManager and updates it. Returns the server's representation of the upgradeManager, and an error, if there is any.
func (c *FakeUpgradeManagers) Update(ctx context.Context, upgradeManager *v1beta2.UpgradeManager, opts v1.UpdateOptions) (result *v1beta2.UpgradeManager, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(upgrademanagersResource, c.ns, upgradeManager), &v1beta2.UpgradeManager{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.UpgradeManager), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeUpgradeManagers) UpdateStatus(ctx context.Context, upgradeManager *v1beta2.UpgradeManager, opts v1.UpdateOptions) (*v1beta2.UpgradeManager, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(upgrademanagersResource, "status", c.ns, upgradeManager), &v1beta2.UpgradeManager{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.UpgradeManager), err
}

// Delete takes name of the upgradeManager and deletes it. Returns an error if one occurs.
func (c *FakeUpgradeManagers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(upgrademanagersResource, c.ns, name), &v1beta2.UpgradeManager{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeUpgradeManagers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(upgrademanagersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta2.UpgradeManagerList{})
	return err
}

// Patch applies the patch and returns the patched upgradeManager.
func (c *FakeUpgradeManagers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta2.UpgradeManager, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(upgrademanagersResource, c.ns, name, pt, data, subresources...), &v1beta2.UpgradeManager{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta2.UpgradeManager), err
}
