/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta2

import (
	longhornv1beta2 "github.com/longhorn/longhorn-manager/k8s/pkg/apis/longhorn/v1beta2"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// EngineTargetLister helps list EngineTargets.
// All objects returned here must be treated as read-only.
type EngineTargetLister interface {
	// List lists all EngineTargets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*longhornv1beta2.EngineTarget, err error)
	// EngineTargets returns an object that can list and get EngineTargets.
	EngineTargets(namespace string) EngineTargetNamespaceLister
	EngineTargetListerExpansion
}

// engineTargetLister implements the EngineTargetLister interface.
type engineTargetLister struct {
	listers.ResourceIndexer[*longhornv1beta2.EngineTarget]
}

// NewEngineTargetLister returns a new EngineTargetLister.
func NewEngineTargetLister(indexer cache.Indexer) EngineTargetLister {
	return &engineTargetLister{listers.New[*longhornv1beta2.EngineTarget](indexer, longhornv1beta2.Resource("enginetarget"))}
}

// EngineTargets returns an object that can list and get EngineTargets.
func (s *engineTargetLister) EngineTargets(namespace string) EngineTargetNamespaceLister {
	return engineTargetNamespaceLister{listers.NewNamespaced[*longhornv1beta2.EngineTarget](s.ResourceIndexer, namespace)}
}

// EngineTargetNamespaceLister helps list and get EngineTargets.
// All objects returned here must be treated as read-only.
type EngineTargetNamespaceLister interface {
	// List lists all EngineTargets in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*longhornv1beta2.EngineTarget, err error)
	// Get retrieves the EngineTarget from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*longhornv1beta2.EngineTarget, error)
	EngineTargetNamespaceListerExpansion
}

// engineTargetNamespaceLister implements the EngineTargetNamespaceLister
// interface.
type engineTargetNamespaceLister struct {
	listers.ResourceIndexer[*longhornv1beta2.EngineTarget]
}
